const games=[
 {id:'pubg',name:'PUBG Mobile',desc:'اشحن شدات ببجي موبايل',c1:'#687e52',c2:'#182426',symbol:'PUBG',packs:[['60 UC','20 دج'],['325 UC','100 دج'],['660 UC','200 دج'],['1800 UC','500 دج'],['3850 UC','1,000 دج'],['8100 UC','2,000 دج']]},
 {id:'freefire',name:'Free Fire',desc:'اشحن جواهر فري فاير',c1:'#8a241e',c2:'#24121a',symbol:'FREE FIRE',packs:[['100 💎','50 دج'],['310 💎','120 دج'],['520 💎','190 دج'],['1060 💎','360 دج'],['2180 💎','700 دج'],['5600 💎','1,650 دج']]},
 {id:'ml',name:'Mobile Legends',desc:'اشحن Diamonds',c1:'#244d91',c2:'#17213b',symbol:'ML',packs:[['86 💎','100 دج'],['172 💎','190 دج'],['257 💎','280 دج'],['706 💎','700 دج'],['2195 💎','2,000 دج'],['5532 💎','4,700 دج']]},
 {id:'football',name:'eFootball',desc:'اشحن العملات',c1:'#193f8c',c2:'#281c4d',symbol:'eFOOTBALL',packs:[['130 Coins','100 دج'],['550 Coins','400 دج'],['1,050 Coins','750 دج'],['2,150 Coins','1,450 دج'],['4,000 Coins','2,600 دج'],['13,000 Coins','7,900 دج']]},
 {id:'genshin',name:'Genshin Impact',desc:'اشحن Genesis Crystals',c1:'#70a4db',c2:'#273f69',symbol:'GENSHIN',packs:[['60 Crystal','120 دج'],['300 Crystal','500 دج'],['980 Crystal','1,500 دج'],['1,980 Crystal','2,900 دج'],['3,280 Crystal','4,500 دج'],['6,480 Crystal','8,700 دج']]},
 {id:'codm',name:'Call of Duty Mobile',desc:'اشحن CP',c1:'#39424b',c2:'#11161a',symbol:'CODM',packs:[['80 CP','120 دج'],['420 CP','500 دج'],['880 CP','950 دج'],['2,400 CP','2,400 دج'],['5,400 CP','5,000 دج'],['11,600 CP','9,900 دج']]},
 {id:'fc',name:'EA Sports FC',desc:'اشحن FC Points',c1:'#5b6063',c2:'#17191b',symbol:'FC 24',packs:[['100 Points','250 دج'],['590 Points','1,100 دج'],['1,050 Points','1,900 دج'],['2,200 Points','3,700 دج'],['4,600 Points','7,200 دج'],['12,000 Points','17,500 دج']]},
 {id:'roblox',name:'Roblox',desc:'اشحن Robux',c1:'#8a8176',c2:'#2b2724',symbol:'ROBLOX',packs:[['80 Robux','180 دج'],['400 Robux','750 دج'],['800 Robux','1,450 دج'],['1,700 Robux','2,900 دج'],['4,500 Robux','7,000 دج'],['10,000 Robux','14,500 دج']]},
 {id:'more',name:'المزيد',desc:'ألعاب إضافية',c1:'#163f3e',c2:'#071516',symbol:'⋯',packs:[]}
];
let selectedGame=games[0], selectedPack=selectedGame.packs[2], cart=0;
const $=s=>document.querySelector(s);
function renderGames(){const wrap=$('#gameStrip');wrap.innerHTML='';games.forEach((g,i)=>{const el=document.createElement('button');el.className='game '+(i===0?'selected':'');el.innerHTML=`<div class="game-cover-art" style="--c1:${g.c1};--c2:${g.c2}">${g.symbol}</div><div class="game-name">${g.name}</div>`;el.onclick=()=>selectGame(g,el);wrap.appendChild(el)});}
function renderPackages(){const wrap=$('#packages');wrap.innerHTML='';if(!selectedGame.packs.length){wrap.innerHTML='<div style="grid-column:1/-1;color:#9db3b0;padding:15px">سيتم إضافة ألعاب أخرى قريباً.</div>';return}selectedGame.packs.forEach((p,i)=>{const el=document.createElement('button');el.className='package '+(i===2?'selected':'');el.innerHTML=`${i===2?'<span class="badge">الأكثر طلباً</span>':''}<strong>${p[0]}</strong><small>${p[1]}</small>`;el.onclick=()=>{document.querySelectorAll('.package').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');selectedPack=p};wrap.appendChild(el)});}
function selectGame(g,el){selectedGame=g;selectedPack=g.packs[2]||null;document.querySelectorAll('.game').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');$('#selectedGame').textContent=g.name;$('#selectedDescription').textContent=g.desc;$('#selectedCover').textContent=g.symbol;$('#selectedCover').style.background=`linear-gradient(145deg,${g.c1},${g.c2})`;renderPackages();document.querySelector('#checkout').scrollIntoView({behavior:'smooth',block:'start'});}
function openModal(){const id=$('#playerId').value.trim();if(!selectedPack){alert('اختر لعبة وباقة متاحة');return}if(!id){alert('أدخل Player ID أولاً');$('#playerId').focus();return}$('#summary').textContent=`اللعبة: ${selectedGame.name} — الباقة: ${selectedPack[0]} — السعر: ${selectedPack[1]} — Player ID: ${id}. بعد إرسال الطلب ستقوم الإدارة بمراجعة إثبات الدفع.`;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false');}
renderGames();renderPackages();
$('#chargeBtn').onclick=openModal;$('#closeModal').onclick=()=>$('#modal').classList.remove('open');$('#confirmBtn').onclick=()=>{cart++;$('#cartCount').textContent=cart;$('#modal').classList.remove('open');alert('تم تسجيل الطلب مبدئياً. اربط Supabase لإرساله فعلياً إلى قاعدة البيانات.');};
$('#search').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll('.game').forEach((el,i)=>el.style.display=games[i].name.toLowerCase().includes(q)?'block':'none')});
$('#proof').addEventListener('change',e=>{if(e.target.files[0]) e.target.closest('.upload').querySelector('strong').textContent='تم اختيار صورة الإثبات ✓'});
